### PR TITLE
chore: Runs eslint --fix, adds example data to .gitignore

### PR DESCRIPTION
**Pull request by lanesawyer**
This PR does two things:
1. Runs `eslint --fix` to fix all linting errors that are easy/non-breaking
2. Adds a few lines to the `.gitignore` for the sample data present after running the tools in the "Running locally" section of the README

The demo app works the same after running the fixes and the build still succeeds, so I'm fairly confident nothing is broken. I've never seen a `--fix` command break anything in the years I've used `eslint`, but it might be good for you to check it against some more substantial datasets.

Eslint output before:
image

After:
image

### CODE REVIEW

**Comment by lanesawyer** [comment]
If you want me to break this into two PRs since it technically deals with separate concerns, I totally can! Or I can name this "improving the developer experience" and then they're in the same bucket of changes 😁

**Comment by bmschmidt** [comment]
Thanks for this! If you'd be able to pull the latest changes and refile the one with the .gitignore changes, I'd be grateful--I had some in-process changes and when I tried to apply the the linting fixes there were a number of conflicts: and it doesn't seem worth manually picking through those. I just ran `eslint --fix` on everything in any case, so that should mostly align with wherever you are now.

**Comment by lanesawyer** [comment]
Done! Curious why there were still some auto fix stuff even though you just ran it an hour ago though...

**Comment by lanesawyer** [comment]
I also went ahead and renamed the remaining `.js` files and ran auto-fix again. If there was a reason to keep those files as `.js`, let me know and I'll revert the last two commits I pushed!

**Comment by lanesawyer** [comment]
Rebased on top of the latest `master`! Anything else I can do to get this PR moving along? I'm planning on starting to tackle a batch of `eslint` errors that can't be autofixed once this is merged.

**Comment by lanesawyer** [comment]
It looks like you're tackling linting in another PR, so the only thing here that _might_ be useful is adding the sample data files to the gitignore.

I'm going to close this PR at this point.

**Pull request closed without merging**
